name: CI/CD Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.UNAME }}
        password: ${{ secrets.PW }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.UNAME }}/spring-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.UNAME }}/spring-app:latest

    # 🚀 FIX LỖI 524 Ở ĐÂY
    - name: Triển khai lên DevOps Classroom
      run: |
        REPO="anhkhoa1604/spring-app"
        CONTAINER_PORT=80

        echo "🚀 Gửi request deploy..."

        curl -X POST "${{ secrets.DEPLOY_URL }}?repo=$REPO&tag=latest&slot=2&container_port=$CONTAINER_PORT&strict_container_port=0" || true

        echo "✅ Đã gửi lệnh deploy. (không chờ server)"
